import Header from './Header'
import Footer from './Footer'
import Hero from './Hero'
import Collections from './Collection'
import Creator from './Creators'
import Categories from './Categories'
import NFT from './NFT'
import Auctions from './Auction'
import Works from './Work/Works'
import MarketplaceNFT from './marketplace'
export { Header,  Hero, Collections, Creator, Categories, NFT, Auctions, Works, MarketplaceNFT,  Footer }